### ISSUE TITLE
Scroll to view when not visible

### ISSUE THREAD

**Issue by deJong-IT** [lekshmiraveendranath/Spotlight#10]
Is there any way to scroll to a view when a target is not visible inside a scrollview and/or stackview?

**Comment by lekshmiraveendranath** [comment]
Spotlight does not tap or interact with the view its highlighting, which is by design. 

But it does provide a delegate mechanism for the viewcontrollers under it to do any action.
```
public protocol SpotlightDelegate: AnyObject {
    func didAdvance(to node: Int, of total: Int)
    func didDismiss()
}
```
Hope the didAdvance(to...) method helps you to re-position the screen to the required part of the screen before Spotlight displays over it.
